default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: projector_dev_db
  username: postgres
  password: root
  host: localhost
  port: 5432

production:
  <<: *default
  database: projector_production_db
  username: postgres
  password: root
  host: localhost
  port: 5432


test:
  <<: *default
  database: projector_test_db
  username: postgres
  # password: root
  host: localhost
  port: 5432
